name: Deploy HTML with Secret

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace placeholder with OPENAI_API_KEY
        run: |
          mkdir output
          sed "s/__OPENAI_KEY__/${{ secrets.OPENAI_API_KEY }}/g" index.html > output/index.html

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
